on: [push]

jobs:
  build-secure-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - run: docker build . -t azure-scanning-poc:latest
      
    - uses: Azure/container-scan@v0
      with:
        image-name: azure-scanning-poc:latest