name: azure-container-scanning

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build-secure-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - run: ls -a #docker build . -t azure-scanning-poc:latest
      
    # - uses: Azure/container-scan@v0
    #   with:
    #     image-name: azure-scanning-poc:latest